### ISSUE TITLE
大佬，glados签到好像凉了，还能抢救吗

### ISSUE THREAD

**Issue by AKA-Cigma** [QikaiXu/YoudaoNote-checkin#4]
![image](https://github.com/QikaiXu/YoudaoNote-checkin/assets/31538893/fc5c1a1c-1eea-48db-a66c-33799b3507bd)

**Comment by letitiaaaa** [comment]
还能抢救吗

**Comment by QikaiXu** [comment]
Glados官方已经修改了签到策略，免费用户不能签到续期了。不让白嫖了 = = 
<img width="691" alt="image" src="https://github.com/QikaiXu/YoudaoNote-checkin/assets/39874073/4eb51bf4-86b0-41ec-a8b8-66c4a2599ba4">

**Comment by lhyhl2** [comment]
请问这种利用action的操作自动签到，需要自己干什么吗？比如需要电脑开机或者登录某个网站吗？
